version: '3.9'

services:
  authapp:
    container_name: authapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - NODE_ENV=stage
    depends_on:
      - mongodb
    networks:
      - auth_network

  mongodb:
    container_name: mongo
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongoadm
      - MONGO_INITDB_ROOT_PASSWORD=mongoadm
    ports:
      - "27017:27017"
    volumes:
      - ./init.js:/docker-entrypoint-initdb.d/init.js:ro
      - ./.dbdata/db:/data/db
    networks:
      - auth_network

networks:
  auth_network:
    driver: bridge
    external: false