version: '3.9'

is_debug: true
listen:
  host: localhost
  port: 9000
mongodb:
  host: localhost
  port: 27017
  username: atuser
  password: atuser
  database: auth
  authdb: auth
  collection: users
secret: asdadsno23029dnksdcsdcln