version: '3.9'

# change config for stage & dev
is_debug: true
listen:
  host: localhost
  port: 9000
mongodb:
  host: mongo
  port: 27017
  username: atuser
  password: atuser
  database: auth
  authdb: auth
  collection: users
secret: asdadsno23029dnksdcsdcln